'use client';

import React, { useState } from 'react';

const GEAR_RATIOS: { [key: number]: { name: string; ratio: number } } = {
  1: { name: '1st Gear', ratio: 2.769 },
  2: { name: '2nd Gear', ratio: 1.882 },
  3: { name: '3rd Gear', ratio: 1.400 },
  4: { name: '4th Gear', ratio: 1.130 },
  5: { name: '5th Gear', ratio: 0.960 },
  6: { name: '6th Gear', ratio: 0.840 },
};

export default function PowertrainCalculator() {
  const [selectedGear, setSelectedGear] = useState<number>(1);
  const [engineTorque, setEngineTorque] = useState<number>(25.0); // Nm
  const [finalDriveRatio, setFinalDriveRatio] = useState<number>(3.428); // 14T / 48T
  const [efficiency, setEfficiency] = useState<number>(90); // 90%
  const [wheelRadius, setWheelRadius] = useState<number>(0.254); // meters (approx 10 inch radius)

  const currentGearRatio = GEAR_RATIOS[selectedGear].ratio;
  const eta = efficiency / 100;

  // Formula 1: T_wheel = T_engine * i_gear * i_final * eta
  const wheelTorque = engineTorque * currentGearRatio * finalDriveRatio * eta;

  // Formula 2: F_tractive = T_wheel / r_wheel
  const tractiveForce = wheelTorque / (wheelRadius || 0.254);

  // Speed estimation at 9,500 RPM
  // Engine RPM to Wheel RPM = RPM / (Primary * Gear * Final)
  // Primary reduction approx 2.800
  const primaryReduction = 2.800;
  const totalReduction = primaryReduction * currentGearRatio * finalDriveRatio;
  const wheelRpmAtRedline = 9500 / totalReduction;
  const speedKmh = ((wheelRpmAtRedline * 2 * Math.PI * wheelRadius) / 60) * 3.6;

  return (
    <div
      className="p-4 p-md-5 rounded"
      style={{
        background: '#FFFFFF',
        border: '2px solid #0F172A',
        boxShadow: '4px 4px 0 #0284C7',
      }}
    >
      <div className="d-flex align-items-center justify-content-between flex-wrap gap-2 mb-4">
        <div>
          <span className="badge-motorsport red mb-1">Live Technical Calculator</span>
          <h4 className="font-orbitron mb-0" style={{ color: '#0F172A', fontWeight: 800 }}>
            CFMOTO 300SR DRIVELINE DYNAMICS SOLVER
          </h4>
        </div>
        <span
          className="badge"
          style={{
            background: '#F0F9FF',
            color: '#0284C7',
            border: '1.5px solid #0284C7',
            fontWeight: 700,
            fontSize: '12px',
          }}
        >
          Section 4 Blueprint Math
        </span>
      </div>

      <p className="small text-muted mb-4">
        Interact with the live transmission parameters below to evaluate rear wheel torque, tractive thrust, and redline gear speeds generated by the CFMoto 292cc single-cylinder power unit.
      </p>

      {/* Gear Selector Buttons */}
      <div className="mb-4">
        <label className="small fw-bold text-uppercase d-block mb-2" style={{ color: '#0F172A', letterSpacing: '0.5px' }}>
          Select Transmission Gear (Sequential 6-Speed):
        </label>
        <div className="d-flex gap-2 flex-wrap">
          {Object.entries(GEAR_RATIOS).map(([gNum, gData]) => {
            const num = Number(gNum);
            const isSelected = selectedGear === num;
            return (
              <button
                key={num}
                type="button"
                onClick={() => setSelectedGear(num)}
                className="btn d-inline-flex flex-column align-items-center"
                style={{
                  background: isSelected ? '#0F172A' : '#F8FAFC',
                  color: isSelected ? '#FFFFFF' : '#0F172A',
                  border: '2px solid #0F172A',
                  boxShadow: isSelected ? '3px 3px 0 #FF2A2A' : '2px 2px 0 #0F172A',
                  padding: '8px 16px',
                  fontWeight: 800,
                  fontSize: '13px',
                  transition: 'all 0.15s ease',
                  borderRadius: '8px',
                }}
              >
                <span>{gData.name}</span>
                <span
                  style={{
                    fontSize: '10.5px',
                    color: isSelected ? '#93C5FD' : '#64748B',
                    fontWeight: 600,
                  }}
                >
                  {gData.ratio.toFixed(3)} : 1
                </span>
              </button>
            );
          })}
        </div>
      </div>

      {/* Input Adjusters Grid */}
      <div className="row g-3 mb-4">
        <div className="col-md-3 col-6">
          <div className="p-3 rounded h-100" style={{ background: '#F8FAFC', border: '1px solid #CBD5E1' }}>
            <label className="small fw-bold d-block text-truncate mb-1" style={{ color: '#0F172A' }}>
              Engine Torque (T<sub>engine</sub>)
            </label>
            <div className="d-flex align-items-center gap-1">
              <input
                type="number"
                step="0.5"
                min="10"
                max="40"
                value={engineTorque}
                onChange={(e) => setEngineTorque(parseFloat(e.target.value) || 0)}
                className="form-control form-control-sm fw-bold"
                style={{ border: '1.5px solid #0F172A', borderRadius: '6px' }}
              />
              <span className="small fw-bold text-muted">Nm</span>
            </div>
            <span className="small text-muted" style={{ fontSize: '10.5px' }}>Nominal: 25.0 Nm</span>
          </div>
        </div>

        <div className="col-md-3 col-6">
          <div className="p-3 rounded h-100" style={{ background: '#F8FAFC', border: '1px solid #CBD5E1' }}>
            <label className="small fw-bold d-block text-truncate mb-1" style={{ color: '#0F172A' }}>
              Final Sprocket Ratio (i<sub>final</sub>)
            </label>
            <div className="d-flex align-items-center gap-1">
              <input
                type="number"
                step="0.05"
                min="2.0"
                max="5.0"
                value={finalDriveRatio}
                onChange={(e) => setFinalDriveRatio(parseFloat(e.target.value) || 0)}
                className="form-control form-control-sm fw-bold"
                style={{ border: '1.5px solid #0F172A', borderRadius: '6px' }}
              />
            </div>
            <span className="small text-muted" style={{ fontSize: '10.5px' }}>14T / 48T = 3.428</span>
          </div>
        </div>

        <div className="col-md-3 col-6">
          <div className="p-3 rounded h-100" style={{ background: '#F8FAFC', border: '1px solid #CBD5E1' }}>
            <label className="small fw-bold d-block text-truncate mb-1" style={{ color: '#0F172A' }}>
              Drivetrain Efficiency (η)
            </label>
            <div className="d-flex align-items-center gap-1">
              <input
                type="number"
                step="1"
                min="70"
                max="98"
                value={efficiency}
                onChange={(e) => setEfficiency(parseFloat(e.target.value) || 0)}
                className="form-control form-control-sm fw-bold"
                style={{ border: '1.5px solid #0F172A', borderRadius: '6px' }}
              />
              <span className="small fw-bold text-muted">%</span>
            </div>
            <span className="small text-muted" style={{ fontSize: '10.5px' }}>Chain &amp; Bearings (88–92%)</span>
          </div>
        </div>

        <div className="col-md-3 col-6">
          <div className="p-3 rounded h-100" style={{ background: '#F8FAFC', border: '1px solid #CBD5E1' }}>
            <label className="small fw-bold d-block text-truncate mb-1" style={{ color: '#0F172A' }}>
              Tire Rolling Radius (r<sub>wheel</sub>)
            </label>
            <div className="d-flex align-items-center gap-1">
              <input
                type="number"
                step="0.005"
                min="0.200"
                max="0.350"
                value={wheelRadius}
                onChange={(e) => setWheelRadius(parseFloat(e.target.value) || 0)}
                className="form-control form-control-sm fw-bold"
                style={{ border: '1.5px solid #0F172A', borderRadius: '6px' }}
              />
              <span className="small fw-bold text-muted">m</span>
            </div>
            <span className="small text-muted" style={{ fontSize: '10.5px' }}>20.0 x 7.0-13 = 0.254 m</span>
          </div>
        </div>
      </div>

      {/* Calculated Performance Output Display */}
      <div className="row g-3">
        <div className="col-md-4 col-12">
          <div
            className="p-3 p-md-4 rounded h-100 text-center"
            style={{
              background: '#0F172A',
              color: '#FFFFFF',
              border: '2px solid #0F172A',
              boxShadow: '3px 3px 0 #FF2A2A',
            }}
          >
            <div className="small fw-bold text-uppercase text-danger mb-1" style={{ letterSpacing: '1px' }}>
              Wheel Torque (T<sub>wheel</sub>)
            </div>
            <div className="font-orbitron" style={{ fontSize: '32px', fontWeight: 900, color: '#FFFFFF' }}>
              {wheelTorque.toFixed(1)} <span style={{ fontSize: '16px', color: '#94A3B8' }}>Nm</span>
            </div>
            <div className="small text-muted mt-1" style={{ fontSize: '11px', color: '#CBD5E1' }}>
              T_engine × i_gear × i_final × η
            </div>
          </div>
        </div>

        <div className="col-md-4 col-12">
          <div
            className="p-3 p-md-4 rounded h-100 text-center"
            style={{
              background: '#0F172A',
              color: '#FFFFFF',
              border: '2px solid #0F172A',
              boxShadow: '3px 3px 0 #0284C7',
            }}
          >
            <div className="small fw-bold text-uppercase mb-1" style={{ color: '#38BDF8', letterSpacing: '1px' }}>
              Tractive Effort (F<sub>tractive</sub>)
            </div>
            <div className="font-orbitron" style={{ fontSize: '32px', fontWeight: 900, color: '#FFFFFF' }}>
              {tractiveForce.toFixed(0)} <span style={{ fontSize: '16px', color: '#94A3B8' }}>N</span>
            </div>
            <div className="small text-muted mt-1" style={{ fontSize: '11px', color: '#CBD5E1' }}>
              T_wheel / r_wheel ({(tractiveForce / 1000).toFixed(2)} kN thrust)
            </div>
          </div>
        </div>

        <div className="col-md-4 col-12">
          <div
            className="p-3 p-md-4 rounded h-100 text-center"
            style={{
              background: '#0F172A',
              color: '#FFFFFF',
              border: '2px solid #0F172A',
              boxShadow: '3px 3px 0 #16A34A',
            }}
          >
            <div className="small fw-bold text-uppercase mb-1" style={{ color: '#4ADE80', letterSpacing: '1px' }}>
              Theoretical Speed @ Redline
            </div>
            <div className="font-orbitron" style={{ fontSize: '32px', fontWeight: 900, color: '#FFFFFF' }}>
              {speedKmh.toFixed(1)} <span style={{ fontSize: '16px', color: '#94A3B8' }}>km/h</span>
            </div>
            <div className="small text-muted mt-1" style={{ fontSize: '11px', color: '#CBD5E1' }}>
              Peak 9,500 RPM in {GEAR_RATIOS[selectedGear].name}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
